#!/bin/bash
set -e

echo "Updating system..."
sudo apt update -y

echo "Installing Docker..."
sudo apt install -y docker.io

echo "Starting Docker..."
sudo systemctl enable docker
sudo systemctl start docker

echo "Pulling Jenkins LTS image..."
sudo docker pull jenkins/jenkins:lts

echo "Running Jenkins container..."
sudo docker run -d \
  --name jenkins \
  -p 8080:8080 \
  -p 50000:50000 \
  jenkins/jenkins:lts

echo ""
echo "Jenkins is starting..."
sleep 15

echo ""
echo "Initial Jenkins Admin Password:"
sudo docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword

echo ""
echo "Open in browser:"
echo "http://<YOUR-EC2-PUBLIC-IP>:8080"
